# Generated by Django 3.0.5 on 2020-04-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='probe',
            name='probegroup',
            field=models.ManyToManyField(through='monitoring.ProbeHostStatus', to='monitoring.Group'),
        ),
    ]
