# Generated by Django 3.0.5 on 2020-04-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_probe_probegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='groupprobe',
            field=models.ManyToManyField(through='monitoring.ProbeHostStatus', to='monitoring.Probe'),
        ),
    ]
