# Generated by Django 3.0.5 on 2020-04-29 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_auto_20200429_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monitoring.Group')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Host')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.Status')),
            ],
        ),
        migrations.RemoveField(
            model_name='probe',
            name='probegroup',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='probehost',
        ),
        migrations.RemoveField(
            model_name='probe',
            name='probestatus',
        ),
        migrations.DeleteModel(
            name='ProbeHostStatus',
        ),
    ]
