# Generated by Django 3.0.5 on 2020-04-29 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_auto_20200429_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monitoring.Group')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Host')),
            ],
        ),
        migrations.DeleteModel(
            name='HostStatus',
        ),
    ]
