# Generated by Django 3.0.5 on 2020-04-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_auto_20200429_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='host',
            field=models.ManyToManyField(null=True, to='monitoring.Host'),
        ),
        migrations.DeleteModel(
            name='HostGroup',
        ),
    ]
