# Generated by Django 3.0.5 on 2020-04-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_auto_20200430_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='host',
            field=models.ManyToManyField(to='monitoring.Host'),
        ),
    ]
