# Generated by Django 3.0.5 on 2020-04-30 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_auto_20200430_0825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='host',
            new_name='hosts',
        ),
    ]
